# Generated by Django 2.2.15 on 2020-08-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('image_id', models.CharField(max_length=100)),
                ('face_id', models.CharField(max_length=100)),
                ('box', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('image_id', models.CharField(max_length=100)),
                ('min_temperature', models.IntegerField(default=30)),
                ('max_temperature', models.IntegerField(default=45)),
                ('image_array', models.TextField(null=True)),
                ('photo_filename', models.CharField(max_length=200)),
                ('thermal_filename', models.CharField(max_length=200)),
                ('photo_output_filename', models.CharField(max_length=200)),
                ('thermal_output_filename', models.CharField(max_length=200)),
                ('covid_detected', models.BooleanField(default=False)),
                ('status', models.CharField(default='processing', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
